POST http://localhost:4000/users
Content-Type: application/json

{
  "password": "hashedpasswordeee",
  "email": "artisan@example.com",
  "role": "customer",
  "profile": {
    "name": "John mark",
    "bio": "Experienced carpenter",
    "location": { "city": "Hong Kong", "address": "gkkkggh" }
  }
}
